### ISSUE TITLE
System.NullReferenceException - LanSensor.PollingMonitor.Program|globalRetryCount

### ISSUE THREAD

**Issue by fymfym** [fymfym/lansensor#6]
2020-04-13 08:02:08.1342|FATAL|LanSensor.PollingMonitor.Program|globalRetryCount:1

2020-04-13 08:02:08.1342|FATAL|LanSensor.PollingMonitor.Program|System.NullReferenceException: Object reference not set to an instance of an object.

   at LanSensor.PollingMonitor.Application.Services.PollingMonitor.Monitors.DataValueToOld.DataValueToOldMonitor.Run(DeviceStateEntity state, DeviceMonitor monitor) in /src/LanSensor.PollingMonitor.Application/Services/PollingMonitor/Monitors/DataValueToOld/DataValueToOldMonitor.cs:line 43

   at System.Linq.Enumerable.Aggregate[TSource,TAccumulate](IEnumerable`1 source, TAccumulate seed, Func`3 func)

   at LanSensor.PollingMonitor.Application.Services.PollingMonitor.PollingMonitor.RunThroughDeviceMonitors() in /src/LanSensor.PollingMonitor.Application/Services/PollingMonitor/PollingMonitor.cs:line 68

   at LanSensor.PollingMonitor.Application.Services.PollingMonitor.PollingMonitor.RunInLoop() in /src/LanSensor.PollingMonitor.Application/Services/PollingMonitor/PollingMonitor.cs:line 100

   at LanSensor.PollingMonitor.Program.Main(String[] args) in /src/LanSensor.PollingMonitor/Program.cs:line 86

**Comment by fymfym** [comment]
fix null value from "GetLatestPresence" now handled correct
